version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env
    volumes:
      - .:/home/node/node_app/app
      - ./package.json:/home/node/node_app/package.json
      - ./package-lock.json:/home/node/node_app/package-lock.json
      - notused:/home/node/node_app/app/node_modules
    links:
      - redis:redis
  redis:
    image: redis
    volumes:
      - redisdata:/data
    restart: always
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"

volumes:
  notused:
  redisdata:
